name: Cypress Automation with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or any version compatible with your project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run --env allure=true

      # Step 5: Install Allure CLI using .tgz
      - name: Install Allure CLI
        run: |
          # Download and extract Allure .tgz archive
          curl -LO https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.22.5/allure-commandline-2.22.5.tgz
          tar -xzf allure-commandline-2.22.5.tgz -C /opt/
          # Add Allure to PATH
          echo "PATH=\$PATH:/opt/allure-2.22.5/bin" >> $GITHUB_ENV
          # Verify installation
          allure --version

      # Step 6: Generate Allure reports
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      # Step 7: Publish Allure Report (optional, using GitHub Pages)
      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
